CompileFlags:
  Add:
    - "-xc++"
    - "-Wall"
    - "-Wunused-variable"
    - "-Wextra"
    - "-Wshadow"
    - "-Wnon-virtual-dtor"
    - "-Wold-style-cast"
    - "-Wcast-align"
    - "-Wunused"
    - "-Woverloaded-virtual"
    - "-Wpedantic"
    - "-Wconversion"
    - "-Wnull-dereference"
    - "-Wdouble-promotion"
    - "-Wformat=2"
    - "-Wmisleading-indentation"
    - "-Wcast-qual"
    - "-Wmissing-declarations"
    - "-Wvla"
    - "-Wwrite-strings"
    - "-Wduplicated-cond"
    - "-Wduplicated-branches"
    - "-Wlogical-op"
    - "-Wrestrict"
    - "-Wunreachable-code"
    - "-pedantic-errors"
    - "-fsanitize=address"
    - "-std=c++17"
    - "--target=x86_64-pc-windows-gnu"
Diagnostics:
  ClangTidy:
    Add:
      - bugprone-*
      - cert-*
      - clang-*
      - cppcoreguidelines-*
      - google-*
      - hicpp-*
      - misc-*
      - modernize-*
      - performance-*
      - readability-*
    Remove:
      - modernize-use-trailing-return-type
      # - cppcoreguidelines-avoid-magic-numbers
      # - cppcoreguidelines-avoid-non-const-global-variables
      # - cppcoreguidelines-init-variables
      - google-build-using-namespace
      # - google-readability-braces-around-statements
      # - hicpp-braces-around-statements
      # - misc-no-recursion
      # - readability-braces-around-statements
      # - readability-magic-numbers
    CheckOptions:
      hicpp-braces-around-statements.ShortStatementLines: 4
      readability-braces-around-statements.ShortStatementLines: 4
      google-readability-braces-around-statements.ShortStatementLines: 4
      
      modernize-use-auto.MinTypeNameLength: 0
      performance-for-range-copy.WarnOnAllAutoCopies: true
      modernize-use-default-member-init.UseAssignment: true
      
      readability-implicit-bool-conversion.AllowIntegerConditions: true
      readability-implicit-bool-conversion.AllowPointerConditions: true

      readability-simplify-boolean-expr.ChainedConditionalReturn: true
      readability-simplify-boolean-expr.ChainedConditionalAssignment: true
      
      readability-identifier-naming.ClassCase: CamelCase
      readability-identifier-naming.ClassMemberCase: lower_case
      readability-identifier-naming.ClassMethodCase: lower_case
      readability-identifier-naming.ConstexprVariableCase: UPPER_CASE
      readability-identifier-naming.EnumCase: CamelCase
      readability-identifier-naming.EnumConstantCase: CamelCase
      readability-identifier-naming.FunctionCase: lower_case
      readability-identifier-naming.GlobalConstantCase: UPPER_CASE
      readability-identifier-naming.MemberConstantCase: UPPER_CASE
      readability-identifier-naming.ParameterCase: lower_case
      readability-identifier-naming.PrivateMemberPrefix: m_
      readability-identifier-naming.StaticConstantCase: UPPER_CASE
      readability-identifier-naming.StructCase: CamelCase
      readability-identifier-naming.TemplateParameterCase: CamelCase
      readability-identifier-naming.UnionCase: CamelCase
      readability-identifier-naming.VariableCase: lower_case
# C:\Users\priyanshu\AppData\Local\clangd